name: sobrenatural-platform

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sobrenatural-backend-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:4016:1337"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: postgres
      DATABASE_HOST: sobrenatural-db
      DATABASE_PORT: 5432
      DATABASE_NAME: sobrenatural
      DATABASE_USERNAME: sobrenatural
      DATABASE_PASSWORD: sobrenatural123
      DATABASE_SSL: "false"
      APP_KEYS: key1,key2,key3,key4
      API_TOKEN_SALT: api-token-salt
      ADMIN_JWT_SECRET: admin-jwt-secret
      TRANSFER_TOKEN_SALT: transfer-token-salt
      JWT_SECRET: jwt-secret
      PUBLIC_URL: https://admin-sobrenatural.busticco.com
    networks:
      - dokploy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sobrenatural-frontend-prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:4015:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      STRAPI_API_URL: http://sobrenatural-backend-prod:1337
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
